---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.10
  - name: centos-6.6
  - name: centos-7.0

suites:
- name: default
  run_list:
      - recipe[sysfs::default]
